version: '3'

services:
  upload-handler:
    build:
      context: ./upload-handler # Specify the directory containing your upload handler Dockerfile
      dockerfile: Dockerfile    # Specify the Dockerfile name if different
    container_name: upload-handler
    image: ""
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    container_name: horizon-database
    ports:
      - "27017:27017"
