version: '3'

services:
  nginx:
    build:
      name: nginx-upload
      context: ./nginx-config   # Specify the directory containing your Nginx Dockerfile
      dockerfile: Dockerfile    # Specify the Dockerfile name if different
    image: nginx:latest
    container_name: nginx-upload
    ports:
      - "1080:1080"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./uploads:/var/www/html/uploads

  upload-handler:
    build:
      name: upload-handler
      context: ./upload-handler # Specify the directory containing your upload handler Dockerfile
      dockerfile: Dockerfile    # Specify the Dockerfile name if different
    container_name: upload-handler
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads  # Map the uploads directory to the script's working directory