version: '3'

services:
  horizon-frontend:
    build:
      context: ./horizon-frontend
      dockerfile: Dockerfile
      tag: horizon-frontend
    container_name: horizon-frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - c2-api
      - user-api
      - file-api
    networks:
      - horizon-network

  c2-api:
    build:
      context: ./c2-api
      dockerfile: Dockerfile
      tag: c2-api
    container_name: c2-api
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    networks:
      - horizon-network

  user-api:
    build:
      context: ./user-api
      dockerfile: Dockerfile
      tag: user-api
    container_name: user-api
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    networks:
      - horizon-network

  file-api:
    build:
      context: ./file-api
      dockerfile: Dockerfile
      tag: file-api
    container_name: file-api
    ports:
      - "8003:8003"
    depends_on:
      - mongo
    networks:
      - horizon-network

  mongo:
    image: docker.io/library/mongo:latest
    container_name: horizon-database
    ports:
      - "27017:27017"
    networks:
      - horizon-network

networks:
  horizon-network:
    driver: bridge
