version: '3'

services:
  horizon-frontend:
    build:
      context: ./horizon-frontend
      dockerfile: Dockerfile
    container_name: horizon-frontend
    ports:
      - "3000:3000"
    depends_on:
      - kafka

  horizon-api:
    build:
      context: ./horizon-api # Specify the directory containing your upload handler Dockerfile
      dockerfile: Dockerfile    # Specify the Dockerfile name if different
      tag: upload-handler
    container_name: horizon-api
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - mongo

  mongo:
    image: mongo:latest
    container_name: horizon-database
    ports:
      - "27017:27017"

  kafka:
    image: confluentinc/cp-kafka
    container_name: horizon-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=upload-handler:1:1,revshell-handler:1:1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: horizon-zookeeper
    ports:
      - "2181:2181"
