version: '3'

services:
  upload-handler:
    build:
      context: ./upload-handler # Specify the directory containing your upload handler Dockerfile
      dockerfile: Dockerfile    # Specify the Dockerfile name if different
    container_name: upload-handler
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads  # Map the uploads directory to the script's working directory

  mongo:
    image: mongo:latest
    container_name: horizon-database
    ports:
      - "27017:27017"
